# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chord.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'chord.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\x12\x05\x63hord\"\x1f\n\x0cHelloRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\nHelloReply\x12\r\n\x05reply\x18\x01 \x01(\t\".\n\nAddRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x05\x12\x0f\n\x07number2\x18\x02 \x01(\x05\"\x1a\n\x08\x41\x64\x64Reply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32u\n\x0c\x43hordService\x12\x33\n\tSendHello\x12\x13.chord.HelloRequest\x1a\x11.chord.HelloReply\x12\x30\n\nAddNumbers\x12\x11.chord.AddRequest\x1a\x0f.chord.AddReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=22
  _globals['_HELLOREQUEST']._serialized_end=53
  _globals['_HELLOREPLY']._serialized_start=55
  _globals['_HELLOREPLY']._serialized_end=82
  _globals['_ADDREQUEST']._serialized_start=84
  _globals['_ADDREQUEST']._serialized_end=130
  _globals['_ADDREPLY']._serialized_start=132
  _globals['_ADDREPLY']._serialized_end=158
  _globals['_CHORDSERVICE']._serialized_start=160
  _globals['_CHORDSERVICE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
